import type { Artisan } from "./types";

/**
 * Sample listings used until the Tourism Department's verified registry is loaded.
 * Real businesses join through /artisans/register → approved on /admin → shown live.
 */
export const SAMPLE_ARTISANS: Artisan[] = [
  {
    id: "ilkal-looms",
    name: { en: "Sangama Ilkal Saree Looms", kn: "ಸಂಗಮ ಇಳಕಲ್ ಸೀರೆ ಮಗ್ಗಗಳು", hi: "संगम इलकल साड़ी करघे" },
    craft: { en: "Ilkal sarees", kn: "ಇಳಕಲ್ ಸೀರೆ", hi: "इलकल साड़ियाँ" },
    description: {
      en: "A weaving family making Ilkal sarees on traditional looms, with the signature red pallu and temple border. Watch the loom at work.",
      kn: "ಸಾಂಪ್ರದಾಯಿಕ ಮಗ್ಗಗಳಲ್ಲಿ ಇಳಕಲ್ ಸೀರೆ ನೇಯುವ ಕುಟುಂಬ — ಕೆಂಪು ಸೆರಗು ಮತ್ತು ಗೋಪುರದ ಅಂಚು ಇದರ ವಿಶೇಷ. ಮಗ್ಗದ ಕೆಲಸವನ್ನು ನೇರವಾಗಿ ನೋಡಿ.",
      hi: "पारंपरिक करघों पर इलकल साड़ी बुनने वाला परिवार — लाल पल्लू और मंदिर-किनारी इसकी पहचान। करघे का काम सामने देखें।",
    },
    category: "weaving",
    town: "Ilkal",
    nearSite: "ilkal",
    lat: 15.9601,
    lng: 76.1149,
    priceHint: "Sarees from ₹1,800",
    languages: ["Kannada", "Hindi"],
    image: "crafts/ilkal-saree",
  },
  {
    id: "ilkal-direct",
    name: { en: "Ilkal Weavers' Direct Store", kn: "ಇಳಕಲ್ ನೇಕಾರರ ನೇರ ಮಳಿಗೆ", hi: "इलकल बुनकर सीधी दुकान" },
    craft: { en: "Sarees & dupattas", kn: "ಸೀರೆ ಮತ್ತು ದುಪಟ್ಟಾ", hi: "साड़ी व दुपट्टे" },
    description: {
      en: "Cotton and cotton-silk Ilkal sarees and dupattas sold straight from the weavers, no middlemen.",
      kn: "ಹತ್ತಿ ಮತ್ತು ಹತ್ತಿ-ರೇಷ್ಮೆ ಇಳಕಲ್ ಸೀರೆ, ದುಪಟ್ಟಾಗಳು ನೇರವಾಗಿ ನೇಕಾರರಿಂದ — ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ.",
      hi: "सूती और सूती-रेशमी इलकल साड़ियाँ व दुपट्टे सीधे बुनकरों से — कोई बिचौलिया नहीं।",
    },
    category: "weaving",
    town: "Ilkal",
    nearSite: "ilkal",
    lat: 15.9578,
    lng: 76.1112,
    priceHint: "From ₹1,200",
    languages: ["Kannada", "Hindi", "English"],
    image: "crafts/handloom",
  },
  {
    id: "khana-weavers",
    name: { en: "Guledgudda Khana Weavers", kn: "ಗುಳೇದಗುಡ್ಡ ಖಣ ನೇಕಾರರು", hi: "गुलेदगुड्ड खण बुनकर" },
    craft: { en: "Khana fabric", kn: "ಖಣ ಬಟ್ಟೆ", hi: "खण कपड़ा" },
    description: {
      en: "Traditional khana blouse fabric woven in rich colours and fine motifs — light, beautiful souvenirs.",
      kn: "ಬಣ್ಣಬಣ್ಣದ, ಸೂಕ್ಷ್ಮ ವಿನ್ಯಾಸದ ಸಾಂಪ್ರದಾಯಿಕ ಖಣ ರವಿಕೆ ಬಟ್ಟೆ — ಹಗುರ, ಸುಂದರ ನೆನಪಿನ ಕಾಣಿಕೆ.",
      hi: "गहरे रंगों और बारीक डिज़ाइन वाला पारंपरिक खण ब्लाउज़ कपड़ा — हल्का, सुंदर स्मृति-चिह्न।",
    },
    category: "weaving",
    town: "Guledgudda",
    nearSite: "guledgudda",
    lat: 16.0515,
    lng: 75.7905,
    priceHint: "Khana pieces from ₹350",
    languages: ["Kannada"],
    image: "crafts/khana-fabric",
  },
  {
    id: "khana-studio",
    name: { en: "Khana Revival Studio", kn: "ಖಣ ಪುನರುಜ್ಜೀವನ ಸ್ಟುಡಿಯೋ", hi: "खण रिवाइवल स्टूडियो" },
    craft: { en: "Khana bags & stoles", kn: "ಖಣ ಚೀಲ ಮತ್ತು ಶಾಲು", hi: "खण बैग व स्टोल" },
    description: {
      en: "Young weavers turning khana into bags, stoles and cushion covers.",
      kn: "ಯುವ ನೇಕಾರರು ಖಣದಿಂದ ಚೀಲ, ಶಾಲು, ದಿಂಬಿನ ಹೊದಿಕೆ ತಯಾರಿಸುತ್ತಾರೆ.",
      hi: "युवा बुनकर खण से बैग, स्टोल और कुशन कवर बनाते हैं।",
    },
    category: "weaving",
    town: "Guledgudda",
    nearSite: "guledgudda",
    lat: 16.0498,
    lng: 75.7881,
    priceHint: "From ₹450",
    languages: ["Kannada", "English"],
    image: "crafts/khana-fabric",
  },
  {
    id: "rotti-oota",
    name: { en: "Chalukya Jolada Rotti Oota", kn: "ಚಾಳುಕ್ಯ ಜೋಳದ ರೊಟ್ಟಿ ಊಟ", hi: "चालुक्य जोलद रोट्टी भोजन" },
    craft: { en: "North Karnataka meals", kn: "ಉತ್ತರ ಕರ್ನಾಟಕ ಊಟ", hi: "उत्तर कर्नाटक भोजन" },
    description: {
      en: "Jowar rotti, ennegai brinjal, pulses, chutney pudi and curd — a true North Karnataka thali.",
      kn: "ಜೋಳದ ರೊಟ್ಟಿ, ಎಣ್ಣೆಗಾಯಿ, ಕಾಳುಪಲ್ಯ, ಚಟ್ನಿಪುಡಿ, ಮೊಸರು — ನಿಜವಾದ ಉತ್ತರ ಕರ್ನಾಟಕ ಊಟ.",
      hi: "ज्वार रोटी, एण्णेगायी बैंगन, दालें, चटनी पुडी और दही — असली उत्तर कर्नाटक थाली।",
    },
    category: "food",
    town: "Badami",
    nearSite: "badami-caves",
    lat: 15.9172,
    lng: 75.6801,
    priceHint: "Meal ₹120–180",
    languages: ["Kannada", "Hindi"],
    image: "crafts/jolada-rotti",
  },
  {
    id: "karadantu",
    name: { en: "Amingad Karadantu Sweets", kn: "ಅಮೀನಗಡ ಕರದಂಟು", hi: "अमीनगड करदंटु मिठाई" },
    craft: { en: "Karadantu sweet", kn: "ಕರದಂಟು", hi: "करदंटु मिठाई" },
    description: {
      en: "The famous Amingad karadantu — edible gum, dry fruits and jaggery, packed for travel.",
      kn: "ಪ್ರಸಿದ್ಧ ಅಮೀನಗಡ ಕರದಂಟು — ಅಂಟು, ಒಣಹಣ್ಣು ಮತ್ತು ಬೆಲ್ಲ, ಪ್ರಯಾಣಕ್ಕೆ ಸೂಕ್ತ ಪ್ಯಾಕಿಂಗ್.",
      hi: "मशहूर अमीनगड करदंटु — गोंद, सूखे मेवे और गुड़, सफ़र के लिए पैक।",
    },
    category: "food",
    town: "Amingad",
    nearSite: "aihole",
    lat: 16.0583,
    lng: 75.9497,
    priceHint: "₹300–600 / box",
    languages: ["Kannada", "Hindi"],
    image: "crafts/karadantu",
  },
  {
    id: "banashankari-snacks",
    name: { en: "Banashankari Temple Street Snacks", kn: "ಬನಶಂಕರಿ ದೇವಸ್ಥಾನ ಬೀದಿ ತಿಂಡಿ", hi: "बनशंकरी मंदिर गली नाश्ता" },
    craft: { en: "Girmit & mirchi bajji", kn: "ಗಿರ್ಮಿಟ್ & ಮಿರ್ಚಿ ಬಜ್ಜಿ", hi: "गिरमिट व मिर्ची बज्जी" },
    description: {
      en: "Girmit, mirchi bajji and fresh sugarcane juice near the temple tank.",
      kn: "ದೇವಸ್ಥಾನದ ಹೊಂಡದ ಬಳಿ ಗಿರ್ಮಿಟ್, ಮಿರ್ಚಿ ಬಜ್ಜಿ ಮತ್ತು ತಾಜಾ ಕಬ್ಬಿನ ಹಾಲು.",
      hi: "मंदिर कुंड के पास गिरमिट, मिर्ची बज्जी और ताज़ा गन्ने का रस।",
    },
    category: "food",
    town: "Banashankari",
    nearSite: "banashankari",
    lat: 15.8871,
    lng: 75.6991,
    priceHint: "₹40–100",
    languages: ["Kannada"],
    image: "crafts/jolada-rotti",
  },
  {
    id: "malaprabha-tea",
    name: { en: "Malaprabha Tea & Snacks", kn: "ಮಲಪ್ರಭಾ ಚಹಾ & ತಿಂಡಿ", hi: "मलप्रभा चाय व नाश्ता" },
    craft: { en: "Coffee & snacks", kn: "ಕಾಫಿ & ತಿಂಡಿ", hi: "कॉफ़ी व नाश्ता" },
    description: {
      en: "Filter coffee, churumuri and lemon soda under the trees near the Pattadakal gate.",
      kn: "ಪಟ್ಟದಕಲ್ಲು ದ್ವಾರದ ಬಳಿ ಮರಗಳ ನೆರಳಲ್ಲಿ ಫಿಲ್ಟರ್ ಕಾಫಿ, ಚುರುಮುರಿ, ನಿಂಬೆ ಸೋಡಾ.",
      hi: "पट्टदकल द्वार के पास पेड़ों की छाँव में फ़िल्टर कॉफ़ी, चुरुमुरी और नींबू सोडा।",
    },
    category: "food",
    town: "Pattadakal",
    nearSite: "pattadakal",
    lat: 15.9476,
    lng: 75.8153,
    priceHint: "₹20–80",
    languages: ["Kannada", "Hindi", "English"],
    image: "crafts/jolada-rotti",
  },
  {
    id: "aihole-homestay",
    name: { en: "Aihole Heritage Homestay", kn: "ಐಹೊಳೆ ಪರಂಪರೆ ಹೋಮ್‌ಸ್ಟೇ", hi: "ऐहोले हेरिटेज होमस्टे" },
    craft: { en: "Village homestay", kn: "ಗ್ರಾಮೀಣ ಹೋಮ್‌ಸ್ಟೇ", hi: "ग्रामीण होमस्टे" },
    description: {
      en: "Stone-house stay with home-cooked meals and sunrise walks among ancient temples.",
      kn: "ಮನೆಯೂಟ ಮತ್ತು ಪ್ರಾಚೀನ ದೇವಾಲಯಗಳ ನಡುವೆ ಸೂರ್ಯೋದಯದ ನಡಿಗೆಯೊಂದಿಗೆ ಕಲ್ಲಿನ ಮನೆಯ ವಾಸ್ತವ್ಯ.",
      hi: "घर का खाना और प्राचीन मंदिरों के बीच सूर्योदय की सैर के साथ पत्थर के घर में ठहराव।",
    },
    category: "homestay",
    town: "Aihole",
    nearSite: "aihole",
    lat: 16.0208,
    lng: 75.8835,
    priceHint: "₹1,500 / night",
    languages: ["Kannada", "Hindi", "English"],
    image: "crafts/homestay",
  },
  {
    id: "malaprabha-farmstay",
    name: { en: "Malaprabha Riverside Farm Stay", kn: "ಮಲಪ್ರಭಾ ನದಿತೀರದ ತೋಟದ ವಾಸ್ತವ್ಯ", hi: "मलप्रभा नदी किनारे फ़ार्म स्टे" },
    craft: { en: "Farm stay", kn: "ತೋಟದ ವಾಸ್ತವ್ಯ", hi: "फ़ार्म स्टे" },
    description: {
      en: "Farm stay by the river with bullock-cart rides, 10 minutes from the UNESCO temples.",
      kn: "ನದಿ ದಡದ ತೋಟದಲ್ಲಿ ವಾಸ್ತವ್ಯ, ಎತ್ತಿನಗಾಡಿ ಸವಾರಿ; ಯುನೆಸ್ಕೋ ದೇವಾಲಯಗಳಿಂದ 10 ನಿಮಿಷ.",
      hi: "नदी किनारे खेत में ठहराव, बैलगाड़ी की सवारी; यूनेस्को मंदिरों से 10 मिनट।",
    },
    category: "homestay",
    town: "Pattadakal",
    nearSite: "pattadakal",
    lat: 15.9522,
    lng: 75.8201,
    priceHint: "₹1,800 / night",
    languages: ["Kannada", "English"],
    image: "crafts/homestay",
  },
  {
    id: "agastya-rooms",
    name: { en: "Agastya Lake View Rooms", kn: "ಅಗಸ್ತ್ಯ ಕೆರೆ ನೋಟದ ಕೊಠಡಿಗಳು", hi: "अगस्त्य झील व्यू कमरे" },
    craft: { en: "Family-run rooms", kn: "ಕುಟುಂಬ ನಡೆಸುವ ಕೊಠಡಿಗಳು", hi: "परिवार द्वारा संचालित कमरे" },
    description: {
      en: "Simple rooms with a rooftop view of Badami's red sandstone cliffs.",
      kn: "ಬಾದಾಮಿಯ ಕೆಂಪು ಮರಳುಗಲ್ಲಿನ ಬಂಡೆಗಳ ಮೇಲ್ಛಾವಣಿ ನೋಟದ ಸರಳ ಕೊಠಡಿಗಳು.",
      hi: "बादामी की लाल बलुआ पत्थर चट्टानों के छत से नज़ारे वाले सादे कमरे।",
    },
    category: "homestay",
    town: "Badami",
    nearSite: "agastya-lake",
    lat: 15.9178,
    lng: 75.6861,
    priceHint: "₹1,200 / night",
    languages: ["Kannada", "Hindi", "English"],
    image: "crafts/homestay",
  },
  {
    id: "sangama-homestay",
    name: { en: "Sangama Pilgrim Homestay", kn: "ಸಂಗಮ ಯಾತ್ರಿಕರ ಹೋಮ್‌ಸ್ಟೇ", hi: "संगम तीर्थयात्री होमस्टे" },
    craft: { en: "Quiet homestay", kn: "ಶಾಂತ ಹೋಮ್‌ಸ್ಟೇ", hi: "शांत होमस्टे" },
    description: {
      en: "Peaceful stay near the river confluence with simple vegetarian meals.",
      kn: "ನದಿ ಸಂಗಮದ ಬಳಿ ಸರಳ ಸಸ್ಯಾಹಾರಿ ಊಟದೊಂದಿಗೆ ಶಾಂತ ವಾಸ್ತವ್ಯ.",
      hi: "नदी संगम के पास सादे शाकाहारी भोजन के साथ शांत ठहराव।",
    },
    category: "homestay",
    town: "Kudalasangama",
    nearSite: "kudalasangama",
    lat: 16.2031,
    lng: 76.0571,
    priceHint: "₹900 / night",
    languages: ["Kannada", "Hindi"],
    image: "crafts/homestay",
  },
  {
    id: "stone-carvers",
    name: { en: "Badami Stone Carvers", kn: "ಬಾದಾಮಿ ಶಿಲ್ಪಿಗಳು", hi: "बादामी शिल्पकार" },
    craft: { en: "Sandstone miniatures", kn: "ಮರಳುಗಲ್ಲಿನ ಕಿರು ಶಿಲ್ಪಗಳು", hi: "बलुआ पत्थर की लघु मूर्तियाँ" },
    description: {
      en: "Hand-carved sandstone miniatures inspired by Chalukya sculpture.",
      kn: "ಚಾಳುಕ್ಯ ಶಿಲ್ಪಕಲೆಯಿಂದ ಪ್ರೇರಿತ, ಕೈಯಿಂದ ಕೆತ್ತಿದ ಮರಳುಗಲ್ಲಿನ ಕಿರು ಶಿಲ್ಪಗಳು.",
      hi: "चालुक्य मूर्तिकला से प्रेरित, हाथ से तराशी बलुआ पत्थर की लघु मूर्तियाँ।",
    },
    category: "crafts",
    town: "Badami",
    nearSite: "badami-caves",
    lat: 15.9191,
    lng: 75.6829,
    priceHint: "From ₹500",
    languages: ["Kannada", "Hindi"],
    image: "crafts/stone-carving",
  },
  {
    id: "lambani",
    name: { en: "Lambani Mirror-Work Collective", kn: "ಲಂಬಾಣಿ ಕನ್ನಡಿ ಕಸೂತಿ ಸಂಘ", hi: "लंबाणी शीशा-कढ़ाई समूह" },
    craft: { en: "Banjara embroidery", kn: "ಬಂಜಾರ ಕಸೂತಿ", hi: "बंजारा कढ़ाई" },
    description: {
      en: "Bright Banjara embroidery with tiny mirrors — bags, wall hangings and stoles.",
      kn: "ಸಣ್ಣ ಕನ್ನಡಿಗಳೊಂದಿಗೆ ಬಣ್ಣಬಣ್ಣದ ಬಂಜಾರ ಕಸೂತಿ — ಚೀಲ, ಗೋಡೆ ಅಲಂಕಾರ, ಶಾಲು.",
      hi: "छोटे शीशों वाली रंगीन बंजारा कढ़ाई — बैग, दीवार सजावट और स्टोल।",
    },
    category: "crafts",
    town: "Badami",
    nearSite: "banashankari",
    lat: 15.8952,
    lng: 75.6921,
    priceHint: "From ₹250",
    languages: ["Kannada", "Lambani", "Hindi"],
    image: "crafts/lambani",
  },
  {
    id: "temple-walks",
    name: { en: "Aihole–Pattadakal Temple Walks", kn: "ಐಹೊಳೆ–ಪಟ್ಟದಕಲ್ಲು ದೇವಾಲಯ ನಡಿಗೆ", hi: "ऐहोले–पट्टदकल मंदिर भ्रमण" },
    craft: { en: "Local heritage guide", kn: "ಸ್ಥಳೀಯ ಪರಂಪರೆ ಮಾರ್ಗದರ್ಶಿ", hi: "स्थानीय विरासत गाइड" },
    description: {
      en: "Two-hour temple walks by a local guide in Kannada, Hindi or English.",
      kn: "ಕನ್ನಡ, ಹಿಂದಿ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಸ್ಥಳೀಯ ಮಾರ್ಗದರ್ಶಿಯಿಂದ ಎರಡು ಗಂಟೆಯ ದೇವಾಲಯ ನಡಿಗೆ.",
      hi: "कन्नड़, हिंदी या अंग्रेज़ी में स्थानीय गाइड के साथ दो घंटे का मंदिर भ्रमण।",
    },
    category: "guide",
    town: "Aihole",
    nearSite: "aihole",
    lat: 16.0195,
    lng: 75.8808,
    priceHint: "₹500 / 2 hrs",
    languages: ["Kannada", "Hindi", "English"],
    image: "sites/aihole",
  },
  {
    id: "sunrise-walks",
    name: { en: "Badami Sunrise Cave & Fort Walks", kn: "ಬಾದಾಮಿ ಸೂರ್ಯೋದಯ ಗುಹೆ & ಕೋಟೆ ನಡಿಗೆ", hi: "बादामी सूर्योदय गुफा व किला भ्रमण" },
    craft: { en: "Early-morning walks", kn: "ಮುಂಜಾನೆ ನಡಿಗೆ", hi: "सुबह की सैर" },
    description: {
      en: "Beat the crowds: sunrise walks to the caves and North Fort with a local guide.",
      kn: "ಜನಸಂದಣಿಗೆ ಮುನ್ನ: ಸ್ಥಳೀಯ ಮಾರ್ಗದರ್ಶಿಯೊಂದಿಗೆ ಗುಹೆಗಳು ಮತ್ತು ಉತ್ತರ ಕೋಟೆಗೆ ಸೂರ್ಯೋದಯ ನಡಿಗೆ.",
      hi: "भीड़ से पहले: स्थानीय गाइड के साथ गुफाओं और उत्तरी किले की सूर्योदय सैर।",
    },
    category: "guide",
    town: "Badami",
    nearSite: "badami-fort",
    lat: 15.9207,
    lng: 75.6846,
    priceHint: "₹400 / 2 hrs",
    languages: ["Kannada", "English"],
    image: "sites/badami-fort",
  },
];

export const TOWN_COORDS: Record<string, { lat: number; lng: number }> = {
  badami: { lat: 15.9179, lng: 75.6789 },
  bagalkote: { lat: 16.1817, lng: 75.6958 },
  aihole: { lat: 16.019, lng: 75.882 },
  pattadakal: { lat: 15.948, lng: 75.8166 },
  ilkal: { lat: 15.9592, lng: 76.1135 },
  guledgudda: { lat: 16.0509, lng: 75.7896 },
  hungund: { lat: 16.0625, lng: 76.0588 },
  kudalasangama: { lat: 16.2046, lng: 76.0592 },
  amingad: { lat: 16.0583, lng: 75.9497 },
  banashankari: { lat: 15.8878, lng: 75.6983 },
  hubballi: { lat: 15.3647, lng: 75.124 },
  vijayapura: { lat: 16.8302, lng: 75.71 },
};
